name: Nuget Push at Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: .NET Restore
        working-directory: ./src
        run: |
          dotnet restore
        
      - name: .NET Build
        working-directory: ./src/Storex.Core
        run: |
          dotnet build --configuration Release --no-restore

      - name: Set
        run : echo "pr_num=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')" >> $GITHUB_ENV 

      - name: Get
        run: echo "${{ env.pr_num }}" 

      - name: .NET Pack
        working-directory: ./src/Storex.Core
        run: |
          dotnet pack --configuration Release --version-suffix pr-${{ github.run_number }}

      - name: Add GitHub Packages source to nuget.config
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/serevo/index.json"
      
      - name: Nuget Push to GitHub Packages
        working-directory: ./src/Storex.Core/bin/Release
        run: dotnet nuget push "Storex.Core.1.0.0-build-${{ github.run_number }}.nupkg" --source "github"
